name: Sync Fork and Build Docker Image

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Sync Fork
        uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MartialBE
          head: main
          base: main
          merge_method: merge
          pr_title: Fork Sync

      - name: Fetch and check for changes
        id: check_changes
        run: |
          git fetch origin main
          UPSTREAM=${1:-'@{u}'}
          LOCAL=$(git rev-parse @)
          REMOTE=$(git rev-parse "$UPSTREAM")
          BASE=$(git merge-base @ "$UPSTREAM")
          
          if [ $LOCAL = $REMOTE ]; then
            echo "Up-to-date"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          elif [ $LOCAL = $BASE ]; then
            echo "Need to pull"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          elif [ $REMOTE = $BASE ]; then
            echo "Need to push"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Diverged"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge changes if any
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main --allow-unrelated-histories

      - name: Set up Docker Buildx
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yx135790mg/one-api:latest

      - name: Trigger Render Deploy
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          echo "Triggering Render Deploy..."
          curl -X POST 'https://api.render.com/deploy/srv-cp7kq5md3nmc73btkiug?key=N2mxexkhecc'
